# Generated by Django 4.0.3 on 2022-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('calorie', models.IntegerField(max_length=50)),
                ('fat', models.IntegerField(max_length=50)),
                ('carbohydrate', models.IntegerField(max_length=50)),
                ('protein', models.IntegerField(max_length=50)),
            ],
        ),
    ]
