# Generated by Django 4.0.3 on 2022-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fruit_calorie_alter_fruit_carbohydrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('total_calorie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_carbohydrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
