# Generated by Django 4.0.3 on 2022-04-15 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 15)),
        ),
    ]
