# Generated by Django 4.0.3 on 2022-05-26 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 26, 16, 14, 16, 799238)),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 26)),
        ),
    ]
